=head1 NAME

oden_wlan_perl - The automatic login tool and library for OECU WiFi

=head1 REQUIREMENT

=over 4

=item * perl - 5.1x or later

=back

=head1 SYNOPSIS

=head2 Installation

You can use this script as install or as-is.

=head3 Installation for Ubuntu

  $ sudo apt-get install git
  $ git clone git://github.com/odentools/oden_wlan_perl.git
  $ cd oden_wlan_perl/
  $ bash install_ubuntu.sh
  
  $ odenwlan --init

=head2 Initial configuration

  $ odenwlan --init
  
  -- Configuration for MC2Wifi --
  
  Please input your MC2 username (ex: ht13a000): ht13a018
  
  Please input your MC2 password: xxxxxxxx
  
  Complete configuration!However, this setting is still unconfirmed.
  
  You must re-configration, if this setting is wrong.
  You can re-configuration with command: $ odenwlan.pl --init
  
  -- Connect to MC2Wifi --
  ~~~~~

=head2 How to use in every day

  $ odenwlan

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2013 OdenTools Project (https://sites.google.com/site/odentools/), Masanori Ohgita (http://ohgita.info/).

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License version 3 (GPL v3).

See LICENSE.txt for details.
