=head1 NAME

oden_wlan_perl - The automatic login tool and library for OECU WiFi

=head1 REQUIREMENTS

This program only supports Linux (such as Ubuntu, Arch Linux, others) in currently.

=head2 Requirements package

These packages are required:

=over 4

=item * perl - 5.1x or later

=item * gnome - 2.x or 3.x (support for proxy setting)

=back

=head1 INSTALLATION

You can use this script as install or as-is.

=head2 Installation for Ubuntu

You can install this program and requirements-package by following steps:

  $ sudo apt-get install git
  $ git clone git://github.com/odentools/oden_wlan_perl.git
  $ cd oden_wlan_perl/
  $ sh install_ubuntu.sh
  
  $ odenwlan --init
  
=head2 Installation for Arch Linux

You can install this program and requirements-package by following steps:

  $ sudo pacman -Syu git
  $ git clone git://github.com/odentools/oden_wlan_perl.git
  $ cd oden_wlan_perl/
  $ sh install_arch-linux.sh
  
  $ odenwlan --init

=head2 Manual installation for other linux-distribution

In this case, first, you must install requirements-package by yourself.

Then, please execute the following:

 $ git clone git://github.com/odentools/oden_wlan_perl.git
 $ cd oden_wlan_perl/
 $ perl Makefile.PL
 $ make
 $ sudo make install

=head2 Updating

You can update this program, by following steps:

 $ git clone git://github.com/odentools/oden_wlan_perl.git
 $ cd oden_wlan_perl/
 $ sh update.sh

=head1 SYNOPSIS

=head2 How to use in every day

  $ odenwlan

=head2 Debug mode

Debug mode is useful for development.

  $ odenwlan --debug

Please add parameter: "--debug" or "-d".

=head2 Initial (re)configuration

  $ odenwlan --init
  
  -- Configuration for MC2Wifi --
  
  Please input your MC2 username (ex: ht13a000): ht13a018
  
  Please input your MC2 password: xxxxxxxx
  
  Complete configuration!However, this setting is still unconfirmed.
  
  You must re-configration, if this setting is wrong.
  You can re-configuration with command: $ odenwlan.pl --init
  
  -- Connect to MC2Wifi --
  ~~~~~

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2013 OdenTools Project (https://sites.google.com/site/odentools/), Masanori Ohgita (http://ohgita.info/).

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License version 3 (GPL v3).

See LICENSE.txt for details.
